<a href="https://colab.research.google.com/github/Dnyaneshwar-zukle/Python-Numpy/blob/main/numpy_%2Bpandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([9,8,6])

In [ ]:
a

array([9, 8, 6])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim # used to check the dimension of an array

1

In [ ]:
b=np.array([[2,8,5],
           [7,9,2]])

In [ ]:
b

array([[2, 8, 5],
       [7, 9, 2]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.ndim

2

In [ ]:
c=np.array([[[4,3,2],
            [4,9,1]],
            
            [[4,5,6],
            [5,2,1]]])

In [ ]:
c

array([[[4, 3, 2],
        [4, 9, 1]],

       [[4, 5, 6],
        [5, 2, 1]]])

In [ ]:
a

array([9, 8, 6])

In [ ]:
x=np.array([5,3,7])

In [ ]:
x

array([5, 3, 7])

In [ ]:
a+x

array([14, 11, 13])

In [ ]:
np.add(a,x)

array([14, 11, 13])

In [ ]:
np.subtract(a,x)

array([ 4,  5, -1])

In [ ]:
np.multiply(a,x)

array([45, 24, 42])

In [ ]:
np.divide(a,x)

array([1.8       , 2.66666667, 0.85714286])

In [ ]:
#element wise

In [ ]:
np.equal(a,x)

array([False, False, False])

In [ ]:
a

array([9, 8, 6])

In [ ]:
x

array([5, 3, 7])

In [ ]:
y=np.array([9,0,6])

In [ ]:
np.equal(a,y)

array([ True, False,  True])

In [ ]:
a

array([9, 8, 6])

In [ ]:
y

array([9, 0, 6])

In [ ]:
# array wise

In [ ]:
np.array_equal(a,x)

False

In [ ]:
a

array([9, 8, 6])

In [ ]:
x

array([5, 3, 7])

In [ ]:
z=np.array([9, 8, 6])

In [ ]:
z

array([9, 8, 6])

In [ ]:
a

array([9, 8, 6])

In [ ]:
np.array_equal(a,z)

True

In [ ]:
np.array_equal(a,y)

False

In [ ]:
a

array([9, 8, 6])

In [ ]:
y

array([9, 0, 6])

In [ ]:
x

array([5, 3, 7])

In [ ]:
y

array([9, 0, 6])

In [ ]:
np.concatenate((x,y))

array([5, 3, 7, 9, 0, 6])

In [ ]:
np.hstack((x,y))
# horizontal

array([5, 3, 7, 9, 0, 6])

In [ ]:
np.vstack((x,y))
#vertical

array([[5, 3, 7],
       [9, 0, 6]])

In [ ]:
x

array([5, 3, 7])

In [ ]:
y

array([9, 0, 6])

In [ ]:
np.vstack((x,y))

array([[5, 3, 7],
       [9, 0, 6]])

In [ ]:
np.row_stack((x,y))

array([[5, 3, 7],
       [9, 0, 6]])

In [ ]:
np.column_stack((x,y))

array([[5, 9],
       [3, 0],
       [7, 6]])

In [ ]:
p=np.array([[9,8,2,1],
           [3,2,1,4],
           [9,8,3,0],
           [9,3,3,2]])

In [ ]:
p

array([[9, 8, 2, 1],
       [3, 2, 1, 4],
       [9, 8, 3, 0],
       [9, 3, 3, 2]])

In [ ]:
np.hsplit(p,2)

[array([[9, 8],
        [3, 2],
        [9, 8],
        [9, 3]]),
 array([[2, 1],
        [1, 4],
        [3, 0],
        [3, 2]])]

In [ ]:
np.vsplit(p,2)

[array([[9, 8, 2, 1],
        [3, 2, 1, 4]]),
 array([[9, 8, 3, 0],
        [9, 3, 3, 2]])]

In [ ]:
p

array([[9, 8, 2, 1],
       [3, 2, 1, 4],
       [9, 8, 3, 0],
       [9, 3, 3, 2]])

In [ ]:
p[0:0+1 , 0:3+1]

array([[9, 8, 2, 1]])

In [ ]:
p[0:1 , 0:4]

array([[9, 8, 2, 1]])

In [ ]:
p[0]

array([9, 8, 2, 1])

In [ ]:
p[2]

array([9, 8, 3, 0])

In [ ]:
p[3]

array([9, 3, 3, 2])

In [ ]:
p[1:1+1,1:2+1]

array([[2, 1]])

In [ ]:
p[1:2,1:3]

array([[2, 1]])

In [ ]:
p[1,1:3]

array([2, 1])

In [ ]:
p[3:3+1,3:3+1]

array([[2]])

In [ ]:
p[3:4,3:4]

array([[2]])

In [ ]:
p[3,3]

2

In [ ]:
p

array([[9, 8, 2, 1],
       [3, 2, 1, 4],
       [9, 8, 3, 0],
       [9, 3, 3, 2]])

In [ ]:
p[1:3,1:3]

array([[2, 1],
       [8, 3]])

In [ ]:
p

array([[9, 8, 2, 1],
       [3, 2, 1, 4],
       [9, 8, 3, 0],
       [9, 3, 3, 2]])

In [ ]:
p[2:4,3:4]

array([[0],
       [2]])

In [ ]:
p[2:4,3]

array([0, 2])

In [ ]:
!pip install  pandas

In [ ]:
import pandas as pd
#pd--> alias / sudo name