<a href="https://colab.research.google.com/github/Dnyaneshwar-zukle/Python-Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to numpy

In [1]:
import numpy as np

In [15]:
myarr = np.array([[1,2,3,4,5,6]], np.int64)

In [8]:
print(type(myarr))

<class 'numpy.ndarray'>


In [16]:
myarr[0, 1]

2

In [17]:
myarr.shape

(1, 6)

#Array creation routines

In [23]:
Listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
Listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
Listarr.dtype

dtype('int64')

In [31]:
Listarr.shape

(3, 3)

In [32]:
Listarr.size

9

In [33]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [54]:
zeros = np.zeros((1,5))

In [55]:
print(zeros)

[[0. 0. 0. 0. 0.]]


In [56]:
zeros.dtype

dtype('float64')

In [57]:
zeros.shape

(1, 5)

In [58]:
zeros

array([[0., 0., 0., 0., 0.]])

In [61]:
rng = np.arange(15)

In [62]:
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [65]:
lspace = np.linspace(1,30,10)

In [66]:
print(lspace)

[ 1.          4.22222222  7.44444444 10.66666667 13.88888889 17.11111111
 20.33333333 23.55555556 26.77777778 30.        ]


In [71]:
emp = np.empty((4,6))

In [72]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [74]:
emp_like = np.empty_like(lspace)

In [75]:
emp_like

array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])